version: "3.8"

services:
  internal-service:
    image: ghcr.io/gaolamthuy/gaolamthuy-internal-service:latest
    container_name: gaolamthuy-api
    restart: always
    expose:
      - ${PORT}
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
