version: "3.8"

services:
  internal-service:
    image: ghcr.io/gaolamthuy/gaolamthuy-internal-service:latest
    container_name: gaolamthuy-api
    restart: always
    expose:
      - ${PORT}
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
