version: "3.8"

services:
  internal-service:
    image: ghcr.io/gaolamthuy/gaolamthuy-internal-service:latest
    container_name: gaolamthuy-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - .env
